-- CreateTable
CREATE TABLE "SystemSettings" (
    "id" TEXT NOT NULL,
    "organizationName" TEXT NOT NULL DEFAULT 'KUCCPS IT Support',
    "organizationCode" TEXT NOT NULL DEFAULT 'KUCCPS',
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#911414',
    "secondaryColor" TEXT NOT NULL DEFAULT '#d20001',
    "supportEmail" TEXT NOT NULL DEFAULT 'itsupport@kuccps.ac.ke',
    "noreplyEmail" TEXT NOT NULL DEFAULT 'noreply@kuccps.ac.ke',
    "emailFromName" TEXT NOT NULL DEFAULT 'KUCCPS IT Support',
    "smtpHost" TEXT NOT NULL DEFAULT 'smtp.gmail.com',
    "smtpPort" INTEGER NOT NULL DEFAULT 587,
    "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
    "smtpUser" TEXT,
    "smtpPassword" TEXT,
    "imapHost" TEXT NOT NULL DEFAULT 'imap.gmail.com',
    "imapPort" INTEGER NOT NULL DEFAULT 993,
    "imapUser" TEXT,
    "imapPassword" TEXT,
    "imapEnabled" BOOLEAN NOT NULL DEFAULT false,
    "imapPollInterval" INTEGER NOT NULL DEFAULT 5,
    "ldapEnabled" BOOLEAN NOT NULL DEFAULT false,
    "ldapUrl" TEXT,
    "ldapBaseDn" TEXT,
    "ldapUserDnPrefix" TEXT,
    "ticketNumberPrefix" TEXT NOT NULL DEFAULT 'TICK',
    "ticketNumberFormat" TEXT NOT NULL DEFAULT 'YYYYMMDD-XXXX',
    "defaultPriority" TEXT NOT NULL DEFAULT 'Medium',
    "defaultCategory" TEXT NOT NULL DEFAULT 'General Issues',
    "googleAddonApiUrl" TEXT,
    "googleAddonEnabled" BOOLEAN NOT NULL DEFAULT false,
    "maxFileSize" INTEGER NOT NULL DEFAULT 10485760,
    "allowedFileTypes" TEXT NOT NULL DEFAULT 'jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,zip',
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "maintenanceMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SystemSettings_pkey" PRIMARY KEY ("id")
);
